# Generated by Django 4.0.3 on 2022-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
