# Generated by Django 4.0.3 on 2022-04-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_attendence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='user',
        ),
    ]
